# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAZ3jZ7V7J7A-2O2oOPLyv6iPbBCmDLt
"""

import streamlit as st

st.title("My First Streamlit Application with text input")

name = st.text_input("Enter your name")

if st.button("Submit"):
	st.success(f"Welcome {name}")
