# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAZ3jZ7V7J7A-2O2oOPLyv6iPbBCmDLt
"""

import streamlit as st
st.title("Salary Prediction")
experience = st.number_input("Years of Experience")

if st.button("Prediction"):
  salary = experience*10000
  st.success(f"Predicted Salary: {salary}")